### ISSUE TITLE
Training compute requirements

### ISSUE THREAD

**Issue by sachit-menon** [mlfoundations/open_flamingo#124]
Hi, great work and really happy to see an open-sourced Flamingo! I was wondering what the compute requirements are, specifically:
- What setup did you train your 9B model on and how long did it take with that setup?
- What ballpark might you estimate training bigger models to need for that? (Any timeline for bigger ones in the works too? 👀)

Thanks!

**Comment by anas-awadalla** [comment]
Hi @sachit-menon,

Thank you for your interest!

1. Our training took place on 32 80GB A100. We trained on 5M samples from MMC4 and 10M from LAION 2B. I don't remember the exact duration it took but it was ~2-3 days.

2. I don't have a specific estimate for compute/timeline for training larger models, I will update as we start to scale things up).

**Comment by sachit-menon** [comment]
Thanks, that's really helpful! Kind of dumb question -- do you have a sense of how far from linear the train-time scaling is (from multi-node communication, etc)? I'm wondering how long it might take with 8 80GB A100s.

**Comment by anas-awadalla** [comment]
Ooh we actually did run these tests a while back and iirc we had very good scaling (it was linear).

**Comment by ZhangYuanhan-AI** [comment]
> 1. 5M

Hi Anas,

I noticed in the README.md that you have utilized 125,000 and 250,000 samples for training, which seems to be the configuration for training the OPT-1.3B model. However, for training the OPT-7B, it appears that you have employed "5 million samples from MMC4 and 10 million from LAION 2B." Could you kindly confirm if my understanding is correct?
```
--train_num_samples_mmc4 125000 \
--train_num_samples_laion 250000 \
```

**Comment by anas-awadalla** [comment]
@ZhangYuanhan-AI This is the number of samples per 'epoch'. Here an epoch refers to how frequently we save a checkpoint so you can really just choose these values depending on how often you want to checkpoint.
