### ISSUE TITLE
Source code license? Separate from Llama license?

### ISSUE THREAD

**Issue by scottjmaddox** [mlfoundations/open_flamingo#125]
I understand that the pre-trained weights are licensed under the Llama license, but what is the source code licensed as? It sounded like you can choose to train a non-Llama backbone. Does the source code under that use case still fall under the Llama license?

Thanks in advance!

**Comment by anas-awadalla** [comment]
Hi @scottjmaddox, no it does not. The license only applies to using the Llama pre-trained weights.
