### ISSUE TITLE
EinopsError in the given demo code

### ISSUE THREAD

**Issue by KzZheng** [mlfoundations/open_flamingo#127]
Hi, when I try to run the demo code in the 'Generating text' section of the readme, I encounter an error:
```
EinopsError:  Error while processing rearrange-reduction pattern "(b T F) v d -> b T F v d".
 Input tensor shape: torch.Size([768]). Additional info: {'b': 1, 'T': 3, 'F': 1}.
 Expected 3 dimensions, got 1
```
The error is happening in the line: https://github.com/mlfoundations/open_flamingo/blob/bc3a89c6622ff47d4e2ebcfe41f130faf872dbd4/open_flamingo/src/flamingo.py#L193

Is it possible to provide a demo python file to show how to use the OpenFlamingo? Thanks!

**Comment by anas-awadalla** [comment]
Can you share the exact code you ran please? I am wondering if there was a typo in how you input the images.

**Comment by KzZheng** [comment]
Sure. I just replaced the llama weights path with my path and do not change any other codes.

```
from open_flamingo import create_model_and_transforms

model, image_processor, tokenizer = create_model_and_transforms(
    clip_vision_encoder_path="ViT-L-14",
    clip_vision_encoder_pretrained="openai",
    lang_encoder_path="/data2/zhengkz/llama_weights_7B_hf",
    tokenizer_path="/data2/zhengkz/llama_weights_7B_hf",
    cross_attn_every_n_layers=4
)

# grab model checkpoint from huggingface hub
from huggingface_hub import hf_hub_download
import torch

checkpoint_path = hf_hub_download("openflamingo/OpenFlamingo-9B", "checkpoint.pt")
model.load_state_dict(torch.load(checkpoint_path), strict=False)

from PIL import Image
import requests

"""
Step 1: Load images
"""
demo_image_one = Image.open(
    requests.get(
        "http://images.cocodataset.org/val2017/000000039769.jpg", stream=True
    ).raw
)

demo_image_two = Image.open(
    requests.get(
        "http://images.cocodataset.org/test-stuff2017/000000028137.jpg",
        stream=True
    ).raw
)

query_image = Image.open(
    requests.get(
        "http://images.cocodataset.org/test-stuff2017/000000028352.jpg", 
        stream=True
    ).raw
)


"""
Step 2: Preprocessing images
Details: For OpenFlamingo, we expect the image to be a torch tensor of shape 
 batch_size x num_media x num_frames x channels x height x width. 
 In this case batch_size = 1, num_media = 3, num_frames = 1 
 (this will always be one expect for video which we don't support yet), 
 channels = 3, height = 224, width = 224.
"""
vision_x = [image_processor(demo_image_one).unsqueeze(0), image_processor(demo_image_two).unsqueeze(0), image_processor(query_image).unsqueeze(0)]
vision_x = torch.cat(vision_x, dim=0)
vision_x = vision_x.unsqueeze(1).unsqueeze(0)

"""
Step 3: Preprocessing text
Details: In the text we expect an <image> special token to indicate where an image is.
 We also expect an <|endofchunk|> special token to indicate the end of the text 
 portion associated with an image.
"""
tokenizer.padding_side = "left" # For generation padding tokens should be on the left
lang_x = tokenizer(
    ["<image>An image of two cats.<|endofchunk|><image>An image of a bathroom sink.<|endofchunk|><image>An image of"],
    return_tensors="pt",
)


"""
Step 4: Generate text
"""
generated_text = model.generate(
    vision_x=vision_x,
    lang_x=lang_x["input_ids"],
    attention_mask=lang_x["attention_mask"],
    max_new_tokens=20,
    num_beams=3,
)

print("Generated text: ", tokenizer.decode(generated_text[0]))
```

**Comment by anas-awadalla** [comment]
@KzZheng I am unable to reproduce your issue. I am wondering if you might have an older version of open_clip as it seems like the output dimension is 768 which I believe is the projection dim of the vision encoder:

https://github.com/mlfoundations/open_flamingo/blob/b95121fef2cd42c5268e5f69aa40ea6cc3fb8a35/open_flamingo/src/flamingo.py#L192

Another thing that might be useful. `self.vision_encoder.visual(vision_x)` returns projection vectors and patch embeddings. We are interested in the latter. Can you print out the shape of both of these outputs for us to check?

**Comment by KzZheng** [comment]
The shape of `vision_x` is [9, 3, 244, 244]. The return of `self.vision_encoder.visual(vision_x)` only has one variable, which has shape [9, 768].

**Comment by KzZheng** [comment]
> @KzZheng I am unable to reproduce your issue. I am wondering if you might have an older version of open_clip as it seems like the output dimension is 768 which I believe is the projection dim of the vision encoder:
> 
> https://github.com/mlfoundations/open_flamingo/blob/b95121fef2cd42c5268e5f69aa40ea6cc3fb8a35/open_flamingo/src/flamingo.py#L192
> 
> Another thing that might be useful. `self.vision_encoder.visual(vision_x)` returns projection vectors and patch embeddings. We are interested in the latter. Can you print out the shape of both of these outputs for us to check?

I re-install the open_clip library but the error is the same.

**Comment by KzZheng** [comment]
Previously, my open_clip_torch = 2.7.0. After I upgrade to 2.16.0, the problem is fixed.
