### ISSUE TITLE
Evaluation results on other supported datasets

### ISSUE THREAD

**Issue by sachit-menon** [mlfoundations/open_flamingo#131]
Hi, do you have results on the other datasets that are already supported in the README? I'm particularly interested in OKVQA.

**Comment by sachit-menon** [comment]
sounds good, thanks!

**Comment by anas-awadalla** [comment]
I got the following results for **validation** performance on OK-VQA
0-shot: 31.16
4-shot: 31.61
8-shot: 34.02
16-shot: 36.52

**Comment by sachit-menon** [comment]
I see, thanks!
________________________________

**Comment by anas-awadalla** [comment]
Resolved in #202. Check out each [model's](https://huggingface.co/openflamingo) readme for evaluation results.
