### ISSUE TITLE
why does vqa_metric.py evaluation compute accuracies wrt each gt answer?

### ISSUE THREAD

**Issue by ericjang** [mlfoundations/open_flamingo#144]
From https://visualqa.org/evaluation.html and https://arxiv.org/pdf/1505.00468.pdf page 4, it seems like the correct way to compute the vqa metric should be something like

```
matchingAns = [item for item in gts[quesId]['answers'] if item['answer'] == resAns]
avgGTAcc = min(1, float(len(matchingAns)) / 3)
```

However, looking at 
https://github.com/mlfoundations/open_flamingo/blob/main/open_flamingo/eval/vqa_metric.py#L421

```
for gtAnsDatum in gts[quesId]["answers"]:
otherGTAns = [
                    item for item in gts[quesId]["answers"] if item != gtAnsDatum
]
matchingAns = [item for item in otherGTAns if item["answer"] == resAns]
acc = min(1, float(len(matchingAns)) / 3)
gtAcc.append(acc)
```

it looks like current gtAcc is computed as "for each ground truth answer, find all the other ground truth answers not equal to it, and then compute the VQA score for those answers, then average VQA scores across all these answers". Why is it computed this way?

**Comment by anas-awadalla** [comment]
Thanks for looking into this @ericjang. We use the [official](https://github.com/GT-Vision-Lab/VQA/blob/master/PythonEvaluationTools/vqaEvaluation/vqaEval.py) vqa accuracy implementation. This is also a bit unintuitive to me so I will dig into it a bit more.

**Comment by anas-awadalla** [comment]
From vqa website:

> In order to be consistent with ‘human accuracies’, machine accuracies are averaged over all 10 choose 9 sets of human annotators. 

I think the current implementation is correct.
