### ISSUE TITLE
VQA v2 Evaluation throwing os error 

### ISSUE THREAD

**Issue by sanyalsunny111** [mlfoundations/open_flamingo#148]
Hey authors,

The VQA eval is throwing an os error in eval_datasets.py in image = Image.open(img_path) could you please fix this ?

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/36811567/229265827-4ec87f6e-aab4-4c8a-b97a-42aa64e2b12b.png">

**Comment by anas-awadalla** [comment]
Hi @sanyalsunny111, I cannot reproduce this issue (despite running on multiple machines). I saw others have been able to run this script successfully so this seems to be a local issue. Sorry about this.

**Comment by sanyalsunny111** [comment]
Hi @anas-awadalla thanks for responding in my understanding it is a bug and below is how I solved it. I have updated the VQADataset class.

class VQADataset(Dataset):
    def __init__(
            self,
            image_dir_path="./VQA/val2014/",
            question_path="./VQA/v2_OpenEnded_mscoco_val2014_questions.json",
            annotations_path="./VQA/v2_mscoco_val2014_annotations.json",
            vqa_dataset="vqa",
    ):
        self.questions = json.load(open(question_path, "r"))["questions"]
        self.answers = json.load(open(annotations_path, "r"))["annotations"]
        self.image_dir_path = image_dir_path
        self.vqa_dataset = vqa_dataset

    def __len__(self):
        return len(self.questions)

    def get_img_path(self, question):
        if self.vqa_dataset == "vqa":
            return os.path.join(
                self.image_dir_path, f"COCO_val2014_{question['image_id']:012d}.jpg"
            )
        elif self.vqa_dataset == "ok_vqa":
            return os.path.join(
                self.image_dir_path, f"COCO_val2014_{question['image_id']:012d}.jpg"
            )
        else:
            raise Exception(f"Unknown VQA dataset {self.vqa_dataset}")

    def __getitem__(self, idx):
        question = self.questions[idx]
        answers = self.answers[idx]
        img_path = self.get_img_path(question)
        with open(img_path, 'rb') as f:
            image = Image.open(f)
            image.load()

        return {
            "image": image,
            "question": question["question"],
            "answers": [a["answer"] for a in answers["answers"]],
            "question_id": question["question_id"],
        }

**Comment by anas-awadalla** [comment]
Got it. I am curious what the issue is?

**Comment by sanyalsunny111** [comment]
The problem : PIL opens image one by one

Solution: In this code, the with statement is used to open the file and read the image data, and it automatically closes the file after the block of code is executed. The load() method is called to ensure that the image data is loaded into memory before closing the file.

**Comment by anas-awadalla** [comment]
Cool thanks for sharing! Are you planning on opening a PR? I can do it if you are not interested :)

**Comment by sanyalsunny111** [comment]
Sure please go ahead and raise a PR.
