### ISSUE TITLE
Can we expect a VQA zeroshot framework using testset and VQA finetuned models

### ISSUE THREAD

**Issue by sanyalsunny111** [mlfoundations/open_flamingo#149]
Hey Authors,

Do you have plans to release 1) zeroshot framework using VQA testset 2) VQA finetuning codes and checkpoints?

**Comment by anas-awadalla** [comment]
1) Yep we are working on it, here is the [issue](https://github.com/mlfoundations/open_flamingo/issues/123)
2) We don't have plans to do this at the moment.

**Comment by sanyalsunny111** [comment]
Hey @anas-awadalla,

I am finetuning flamingo-LLaMA-7B 5M model on my own GPUs and once it is done I will happy to share the finetuning code and the checkpoints to this repo and huggingface. Can you answer a question for me please I am a bit stuck here.

1) Since VQA has multiple answers to every question do you know what is the right way to feed answers to the model?
2) Also how to generate labels for the model in case of VQA?

**Comment by anas-awadalla** [comment]
@sanyalsunny111 Cool! This would be awesome.

1. I think just randomly picking an answer should be fine.
2. For VQA you can format your samples as "<image>Question: some question? Answer: some answer". You really should only compute loss on the "some answer" portion. 

**How we currently do this?**
After you run your input through the tokenizer you should get input_ids and the way we turn these into labels for LAION is to do:
```
labels = input_ids.clone()
labels[labels == tokenizer.pad_token_id] = -100. # don't take loss on padding tokens
labels[:, 0] = -100 # don't take loss on BOS token
labels[labels == media_token_id] = -100 # don't take loss on <image> token
```

**What is missing?**
I think what you need to add is a way to mask loss on everything other than the answer. This will be a bit tricky to do from the tokens. Maybe adding some special token to the prompt to be able to determine where the answer starts could be a good approach. Something like "<image>some question?<special_answer_token>some answer" and maybe at that point there is no need to include the "Question:" and "Answer:" prefixes.
