### ISSUE TITLE
No access for repository

### ISSUE THREAD

**Issue by archana53** [mlfoundations/open_flamingo#150]
When I try to run the exact same code snippet from README, I get the following error:

RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-642dce11-72831d6a4c49abfd3cc776f4)

Repository Not Found for url: https://huggingface.co/openflamingo/OpenFlamingo-9B/resolve/main/checkpoint.pt.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
Invalid username or password.

Is there some access request we need to make or am I missing something here?

**Comment by anas-awadalla** [comment]
The repo is gated so you will need to create a HuggingFace account and make an [access request](https://huggingface.co/openflamingo/OpenFlamingo-9B) before you are able to load the model.

**Comment by Ryosuke0104** [comment]
Hi, I'm Hugging Face beginner.
I can't understand how to make an access request.
I got same error.
Please let me know how to make a requset.

Thank you for your kindness.
