### ISSUE TITLE
Timeline for dataset releasing

### ISSUE THREAD

**Issue by liuguilin1225** [mlfoundations/open_flamingo#152]
Thanks a lot for the amazing work. I am wondering when the MultiModal C4 dataset and bipartite matching filtering script will be released. Thanks.

**Comment by liuguilin1225** [comment]
Just notice that the author relied the dataset released timeline at #151 
Is there a plan to release the bipartite matching filtering script as well? 
Thanks.

**Comment by VegB** [comment]
Hi, thanks for asking!

We plan to release the Multimodal-C4 dataset next week, but the processing scripts might not come with the initial release.

Here's the bipartite matching snippet from a closely-related work (our implementation is largely the same, except for a few extra unit tests) -- hope you find it useful: [https://github.com/jmhessel/multi-retrieval/blob/master/bipartite_utils.py](https://github.com/jmhessel/multi-retrieval/blob/master/bipartite_utils.py)

**Comment by VegB** [comment]
Hi, the MultimodalC4 repo is public now: [https://github.com/allenai/mmc4](https://github.com/allenai/mmc4).

**Comment by liuguilin1225** [comment]
Thanks a lot for letting me know and your hard work on this dataset. Look forward to exploring more about this dataset.
