### ISSUE TITLE
coco few shot evaluation replicated images

### ISSUE THREAD

**Issue by yingfhu** [mlfoundations/open_flamingo#153]
Question about the replicated examples in eval. Since the few shot validation support and query sets are both sampled from `train2017.json` annotations, but every image have 5 annotations, there might be small chance that support image is the same as query image but with different annotations,  this might lead to higher metric result.

**Comment by jpgard** [comment]
@yonatanbitton is there a fix we could make for this?

**Comment by anas-awadalla** [comment]
I have a fixed for this that I will push soon.

**Comment by anas-awadalla** [comment]
fixed a while back
