### ISSUE TITLE
Evaluation results seems abnormal on vqa_v2

### ISSUE THREAD

**Issue by lziiid** [mlfoundations/open_flamingo#154]
Hi, thanks for the open-source model and weights!
I evaluate on vqa_v2 validation set, using the llama-7b weights from huggingface. When using 0-shot, the score is 43.35; but 1-shot, 2-shot, and 4-shot are only 29.11, 36.21, and 42.27, even lower than 0-shot. I am curious whether the result is reasonable?
Here are the related args in config I use:
`python open_flamingo/eval/evaluate.py \
    --eval_vqav2 \
    --num_samples 5000 \
    --shots 0 \
    --num_trials 1 \
    --batch_size 4 \
`

**Comment by tcShen** [comment]
Hello, lziiid. How about your results now? Have you found or fixed any problems?
I also find similar results to you (The performance of 4-shot is lower than 0-shot. ). Thanks

**Comment by lziiid** [comment]
> Hello, lziiid. How about your results now? Have you found or fixed any problems? @lziiid I also find similar results to you (The performance of 4-shot is lower than 0-shot. ). Thanks

No, I haven't found the problem :(

**Comment by jpgard** [comment]
@yonatanbitton might have thoughts/suggestions here.

**Comment by anas-awadalla** [comment]
Should be resolved in #202
