### ISSUE TITLE
requirements update proposal

### ISSUE THREAD

**Issue by HUGHNew** [mlfoundations/open_flamingo#157]
https://github.com/mlfoundations/open_flamingo/blob/25a05342373757a5bef3bf51eda4bc6c545e75f7/requirements.txt#L3

transformers -> git+https://github.com/huggingface/transformers.git

Since `LlamaTokenizer` is not in  released in PyPI now, I propose replace "transformers" with "git+https://github.com/huggingface/transformers.git" to simplify the install procedure.

But I have no idea about how to modify the setup.py.

**Comment by anas-awadalla** [comment]
Thanks, I think this is no longer needed. It is released now and I have made the changes [here](https://github.com/mlfoundations/open_flamingo/pull/164).
