### ISSUE TITLE
If I change the LLM model to llama-30B, need to retrain the model?

### ISSUE THREAD

**Issue by trouble-maker007** [mlfoundations/open_flamingo#159]
If I change the LLM model to llama-30B, need to retrain the model?

**Comment by ludwigschmidt** [comment]
Yes, you would need to re-train the model. Releasing OpenFlamingo models with larger LLMs is on our agenda!

**Comment by trouble-maker007** [comment]
@ludwigschmidt thank you for the response, I still have question about that how many gpus use for training and how long for training?

**Comment by anas-awadalla** [comment]
https://github.com/mlfoundations/open_flamingo/issues/124
