### ISSUE TITLE
create_model_and_transforms is super slow...

### ISSUE THREAD

**Issue by ethanyanjiali** [mlfoundations/open_flamingo#160]
Just want to report this. I will do some profiling later, but want to see if the team has any insights on this

**Comment by ethanyanjiali** [comment]
It was a lot faster when I run in Jupyter notebook.

**Comment by ethanyanjiali** [comment]
turn out to be the autotokenizer initialization. 
open_clip.create_model_and_transforms 8.05569052696228
AutoTokenizer.from_pretrained 225.26867389678955
AutoModelForCausalLM.from_pretrained 54.45951008796692

setting use_local_files to True doesn't really help. My LLaMA tokenizer file is local and I'm using open_clip_torch 2.16.0

**Comment by anas-awadalla** [comment]
Thanks for investigating! It is very weird that the tokenizer takes so much time we will keep an eye on this.

**Comment by XinyangHan** [comment]
Same problem as well!!

**Comment by jpgard** [comment]
I'm going to close this for now, since this seems to be unrelated to OpenFlamingo. Feel free to reopen if there is something on our end causing the slowness that we can address.
