### ISSUE TITLE
without LLaMA

### ISSUE THREAD

**Issue by sasakits** [mlfoundations/open_flamingo#166]
Hi Thanks for your great work. I could use a sample code with LLaMA. 
After that, I am trying to do it without LLaMA, for example opt-125m case, I faced with below error.
What should I do in the case of using without LLaMA?

```
RuntimeError: Error(s) in loading state_dict for Flamingo:
	size mismatch for lang_encoder.gated_cross_attn_layers.3.attn.norm.weight
```

**Comment by anas-awadalla** [comment]
The checkpoint we provide is specific to the llama 7B model. For a different language model you will need to train your own flamingo model.
