### ISSUE TITLE
use open_flamingo for open-ended VQA

### ISSUE THREAD

**Issue by dst111dst** [mlfoundations/open_flamingo#167]
Hi thanks for your excellent work!

I'm currently working on open-ended VQA, and I found that a history version included a demo based on `streamlit`. But the function in this demo didn't match the version of current open\_flamingo, which made me really confused.

![image](https://user-images.githubusercontent.com/72456015/232265164-336da358-02a1-48bb-969b-25ab8410d88f.png)
<img width="773" alt="Screenshot 2023-04-15 at 8 40 09 PM" src="https://user-images.githubusercontent.com/72456015/232265172-e6c601cd-41b5-4055-89b8-3c90cc75013d.png">

And I referred to the `eval` folder for the evaluation of VQA. But it seems that the evaluation methods are built on the labeled datasets, and they can't generate a textual answer for a picture outside of the datasets. 

So,Is there any attempts like the demo for open-ended VQA problem? Thanks a lot for your reply!

**Comment by anas-awadalla** [comment]
Hello,

Yes the code in this older version of the repo will not work for the current models. 

I am not sure I completely understand your use case though, can you clarify? If you are just trying to do visual question answering on your own dataset then can you adapt the example in the [Readme](https://github.com/mlfoundations/open_flamingo#generating-text) to do this?

**Comment by dst111dst** [comment]
> Hello,
> 
> Yes the code in this older version of the repo will not work for the current models.
> 
> I am not sure I completely understand your use case though, can you clarify? If you are just trying to do visual question answering on your own dataset then can you adapt the example in the [Readme](https://github.com/mlfoundations/open_flamingo#generating-text) to do this?

Ok that's what I'm tring to do :) Thanks for your suggestions! I'm sry for my lack of clarity, yeah I'm trying to use the model for new dataset. And for this example, I have another question: the input format of `tokenizer` is different in **Image Caption** and **VQA**  ( The `input_ids` below was in the history version of `demo.py`, the `lang_x` is in this [example](https://github.com/mlfoundations/open_flamingo#generating-text) )->
<img width="803" alt="Screenshot 2023-04-15 at 11 23 30 PM" src="https://user-images.githubusercontent.com/72456015/232276615-957772fb-9372-4118-bf35-45044727ac55.png">

So is it appropriate to use the tokenizer in the same format?
My adaption of this example is as follows:
```
question = "What is the animal?"
encodings = tokenizer(
            question,
            return_tensors="pt",
            padding="longest",
            truncation=True,
            max_length=2000,
)

input_ids = encodings["input_ids"].to(device)
attention_mask = encodings["attention_mask"].to(device)
max_generation_length = 100
num_beams = 1
length_penalty = 1.0

outputs = get_outputs(
            model=model,
            batch_images=vision_x,
            device=device,
            attention_mask=attention_mask,
            max_generation_length=max_generation_length,
            num_beams=num_beams,
            length_penalty=length_penalty,
            input_ids=input_ids,
)
```

**Comment by anas-awadalla** [comment]
If I am going to adapt the readme example for vqa I would do the following

```
from PIL import Image
import requests

"""
Step 1: Load images
"""
demo_image_one = Image.open(
    requests.get(
        "http://images.cocodataset.org/val2017/000000039769.jpg", stream=True
    ).raw
)

demo_image_two = Image.open(
    requests.get(
        "http://images.cocodataset.org/test-stuff2017/000000028137.jpg",
        stream=True
    ).raw
)

query_image = Image.open(
    requests.get(
        "http://images.cocodataset.org/test-stuff2017/000000028352.jpg", 
        stream=True
    ).raw
)


"""
Step 2: Preprocessing images
Details: For OpenFlamingo, we expect the image to be a torch tensor of shape 
 batch_size x num_media x num_frames x channels x height x width. 
 In this case batch_size = 1, num_media = 3, num_frames = 1 
 (this will always be one expect for video which we don't support yet), 
 channels = 3, height = 224, width = 224.
"""
vision_x = [image_processor(demo_image_one).unsqueeze(0), image_processor(demo_image_two).unsqueeze(0), image_processor(query_image).unsqueeze(0)]
vision_x = torch.cat(vision_x, dim=0)
vision_x = vision_x.unsqueeze(1).unsqueeze(0)

"""
Step 3: Preprocessing text
Details: In the text we expect an <image> special token to indicate where an image is.
 We also expect an <|endofchunk|> special token to indicate the end of the text 
 portion associated with an image.
"""
tokenizer.padding_side = "left" # For generation padding tokens should be on the left
lang_x = tokenizer(
    ["<image>Question: What animal is this? Answer: cat<|endofchunk|><image>Question: What is this? Answer: bathroom<|endofchunk|><image>Question: What is on the table? Answer:"],
    return_tensors="pt",
)


"""
Step 4: Generate text
"""
generated_text = model.generate(
    vision_x=vision_x,
    lang_x=lang_x["input_ids"],
    attention_mask=lang_x["attention_mask"],
    max_new_tokens=20,
    num_beams=3,
)

print("Generated text: ", tokenizer.decode(generated_text[0]))
```

Hope this helps. Please do not refer to the streamlit example for code!

**Comment by dst111dst** [comment]
I'm so sorry for seeing this reply so late :((( 

Thanks for your suggestions! It works well on the given example :)))
