### ISSUE TITLE
Opt version of Flamingo!

### ISSUE THREAD

**Issue by ermu2001** [mlfoundations/open_flamingo#171]
I explored in the code that once there was a Facebook/opt-1.3b version of open-flamingo.

Due the constraints of my computing resources, I cannot successfully execute llama T.T. Would you kindly inform me whether the smaller version of open-flamingo will be open sourced in the future?

💗

**Comment by anas-awadalla** [comment]
Thanks for bringing this up! Yes I think this is something we can do in our upcoming releases :).

**Comment by ermu2001** [comment]
thank you so much! looking forwards to it~

🙏
