### ISSUE TITLE
Vision Encoder Shape Issue

### ISSUE THREAD

**Issue by achen46** [mlfoundations/open_flamingo#173]
Hi, thanks for the great work. 

I have run into some issues withe vision encoder part. Specifically, given a simple input image of shape [8,3,224,224] (following the example from your provided command in ReadMe), the output of this [line](https://github.com/mlfoundations/open_flamingo/blob/main/open_flamingo/src/flamingo.py#L192) is just [768]. Hence, the reshaping is not possible in [this](https://github.com/mlfoundations/open_flamingo/blob/main/open_flamingo/src/flamingo.py#L193).

In essence, the output of `self.vision_encoder.visual(vision_x)` is [8,768]. What is wrong here ? I suppose we need the output of last hidden state and not the vision encoder ? I would appreciate if you could help ( and maybe this could be a bug).

**Comment by achen46** [comment]
For reference, I am simply running this command and only training on laion dataset (which should not matter here):

```
torchrun --nnodes=1 --nproc_per_node=1 train.py \
--run_name flamingo3B \
--lm_path facebook/opt-1.3b \
--tokenizer_path facebook/opt-1.3b \
--dataset_resampled \
--laion_shards "path_to_dataset" \
--batch_size_laion 8 \
--train_num_samples_mmc4 0 \
--train_num_samples_laion 50000 \
--loss_multiplier_laion 1.0 \
--workers=6 \
--num_epochs 250 \
--lr_scheduler constant \
--warmup_steps 5000 \
--mmc4_textsim_threshold 0
```

**Comment by anas-awadalla** [comment]
This seems similar to [this](https://github.com/mlfoundations/open_flamingo/issues/127). Can you upgrade your open_clip package? I should also open a PR to fix this in the requirements.

**Comment by achen46** [comment]
@anas-awadalla Thank you so much for your speedy response :+1:  Yes it did solve the problem by upgrading the open_clip package :)
