### ISSUE TITLE
Multi-node Training Command

### ISSUE THREAD

**Issue by achen46** [mlfoundations/open_flamingo#176]
Hi, I wonder if you could provide a sample multi-node training command for training the open_flamingo model ? testing with torchrun, the job hangs hence would like to understand if any additional changes need to be made in the code. 

Thanks

**Comment by anas-awadalla** [comment]
hmm no additional changes needed. Can you give me a bit more detail about where the job hangs? Is there anything logged at that point? Have you modified the script in any way (maybe to train just on laion or something like that)?

**Comment by evelinehong** [comment]
Hey

Same problem here. Have you solved it?

**Comment by anas-awadalla** [comment]
Hello I am trying to figure out what the problem is. Can you answer the questions [here](https://github.com/mlfoundations/open_flamingo/issues/176#issuecomment-1517160394) so I can help debug :)?

**Comment by evelinehong** [comment]
I managed to solve it by adding MASTER_ADDR (and without MASTER_PORT)

**Comment by ShramanPramanick** [comment]
Hi @evelinehong, can you please elaborate more on how you solved this problem (where did you add MASTER_ADDR)? Thanks in advance.
