### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by 2132660698** [mlfoundations/open_flamingo#180]
wen run this:
![image](https://user-images.githubusercontent.com/94035926/233941842-6ed74957-0910-4201-8c66-3d372c79cfbb.png)

then error:

![image](https://user-images.githubusercontent.com/94035926/233941930-508b3bb3-bc47-48a9-876c-ae4879fc07c4.png)

I use this lama model. [https://huggingface.co/luodian/llama-7b-hf/tree/main](url)

**Comment by anas-awadalla** [comment]
It seems that you need to move your vision_x and lang_x inputs to gpu.
