### ISSUE TITLE
[BUG] Generation Config Parameters: How to generate like your demo?

### ISSUE THREAD

**Issue by cliangyu** [mlfoundations/open_flamingo#183]
## Expected Behavior

As shown in your gradio demo, the model is supposed to generate concise answers.

## Current Behavior

We attempted to run the code demo in README.
```python
"""
Step 4: Generate text
"""
generated_text = model.generate(
    vision_x=vision_x,
    lang_x=lang_x["input_ids"],
    attention_mask=lang_x["attention_mask"],
    max_new_tokens=20,
    num_beams=3,
)
```
The output is repetitive and of low quality.
<img width="886" alt="image" src="https://user-images.githubusercontent.com/45140242/234301100-6404029f-2c30-4dd0-8b47-9ab71b98a632.png">

## Steps to Reproduce

See the code demo in README.

**Comment by dheerajpant700** [comment]
Is it resolved now. I am facing similar issue.

**Comment by cliangyu** [comment]
I don't think so. Looks like a model issue.

**Comment by anas-awadalla** [comment]
Sorry for the late response! Yes it is a bug with the current checkpoint and we are working on fixing it in our next release. Sorry about that! For the time being you can use this [workaround](https://github.com/mlfoundations/open_flamingo/issues/147).

**Comment by chaojiewang94** [comment]
Is it resolved now? or someother checkpoint I can use?
