### ISSUE TITLE
Downloading checkpoint file from hf_hub_download() takes over 1.5 hours each time inference is run. Also, GPUs not working

### ISSUE THREAD

**Issue by roboswell** [mlfoundations/open_flamingo#186]
# Problem:

When using the inference code on the Open Flamingo GitHub repo, I have been able to verify that the line which reads checkpoint_path = hf_hub_download("openflamingo/OpenFlamingo-9B", "checkpoint.pt") literally takes over 1.5 hours each time it is run while trying to perform inference. 

It is unclear if CUDA can be attached to hf_hub_download to increase download speed.

## Expected Behavior

Correct me if I am wrong, but shouldn't downloading checkpoint_path = hf_hub_download("openflamingo/OpenFlamingo-9B", "checkpoint.pt") not take very much time? Would I need to use the argument cache_dir for hf_hub_download for the checkpoint_file to be cached and ready to rapidly load every other time once downloaded?

## Current Behavior

It is not only that hf_hub_download takes 1.5 hours to run, but in addition, CUDA does not appear to be working at all for your recommended "Initializing an OpenFlamingo model" and "Generating text" code, as verified by using the linux code: watch nvidia-smi.

Even when using map_location="cuda" for torch.load() and attaching .to("cuda") to model, to vision_x = torch.cat(vision_x, dim=0), and to lang_x = tokenizer(), CUDA is not running.

Despite the length of time to run the code, in the end inference does occur successfully.

## Environment

I am using a Docker container to do this. The Docker image I am using is pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime (for ubuntu), while pip installing open-flamingo, huggingface-hub, requests, and Pillow.

**Comment by Marcusntnu** [comment]
I dont have the exact same problem, I load the hub model in ca 10min, but the inference is vert slow with me too, and the GPU utilization is only at around 36%. Takes a very very long time for me to do inference over a small dataset.

**Comment by roboswell** [comment]
I don't know why inference runs so slowly on your computer. But, I wonder (@anas-awadalla), should it even take 10 minutes for the checkpoint to be downloaded from huggingface_hub each time? Shouldn't it be cached after downloading the very first time, so that the model will load quickly every time after that? If so, do we need to specify the hf_hub_download arguments "cache_dir" and/or "local_dir" and/or "local_dir_use_symlinks" in order for the model to load rapidly? I do not see these arguments being used on the Open Flamingo GitHub example code under "Initializing an OpenFlamingo model".

**Comment by anas-awadalla** [comment]
@roboswell No it should be cached! Maybe you can take a look at your huggingface cache and see if it is there? Yeah using local_dir is a good workaround. Also can you explain what you mean by cuda is not working? What do you see when using nvidia-smi?

**Comment by roboswell** [comment]
@anas-awadalla Yeah, here is an nvidia-smi output screenshot of the GPU I am trying to use:
![image](https://user-images.githubusercontent.com/72875675/236557498-ce88880e-e7b9-4704-9a89-262aaa1bfea4.png)
GPU utilization ALWAYS remains at 0% throughout the entire process of running the code to initialize the model and perform inference. Sometimes, memory usage is completely at 0, while other times it does register some memory usage (as shown in the image).

Correct me if I'm wrong, but I'm doubtful that GPUs can be used to speed up the downloading process of Open Flamingo 9B since GPUs are usually used for computation. But, even if GPUs cannot be used for parallelization for the downloading process for hf_hub_download() files, is there some way to use parallelization for the checkpoint download? When I run the code, my screen shows the checkpoint as a 5.24 GB file, which is why it's taking 1.5 hours to download.

**Comment by roboswell** [comment]
Using local_dir, it looks I've got it cached properly now, as it no longer takes 1.5 hours to download the checkpoint from hf_hub_download. However, I'm receiving an error that seems strange.  The error occurs on model.generate(): The error states:
 
`AttributeError: 'GELU' object has no attribute 'approximate'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 221) of binary: /opt/conda/bin/python`

Has anyone else been receiving this error?
