### ISSUE TITLE
[BUG] YOUR DESCRIPTION HERE

### ISSUE THREAD

**Issue by happyday127** [mlfoundations/open_flamingo#191]
I noticed that the CLIP features can be obtained from the mmc4 GitHub page for downloading. The link to access the features is: https://storage.googleapis.com/ai2-jackh-mmc4-public/images/clip_vitl14_shard_{$SHARD}_features.pkl. However, I would like to inquire for updating the script that converts the combined wwc4 document_shard jsonl files and wwc4 CLIP feature pickle files into the WebDataset format. Because the script still requires the "--image_shards" (raw image shard) argument, and has no argument for taking in the CLIP feature shards.

**Comment by jpgard** [comment]
Please fill in a descriptive title for this issue. Thanks!

**Comment by jpgard** [comment]
Please also follow our issue [template](https://github.com/mlfoundations/open_flamingo/issues/new) if you'd like to file a bug report.

**Comment by anas-awadalla** [comment]
It seems like this is a duplicate of [this](https://github.com/mlfoundations/open_flamingo/issues/168#issuecomment-1530391095). Closing for now.
