### ISSUE TITLE
Pre-downloading all weights - IncompatibleKeys(missing_keys ....)

### ISSUE THREAD

**Issue by mohbattharani** [mlfoundations/open_flamingo#204]
My compute server does not allow direct download from Huggingface or any link. So, I have to download all weights on local system and copy to server. So, I have downloaded weights from following places:

- llama7B: https://huggingface.co/yahma/llama-7b-hf/tree/main
- ViT-L-14: [openai](https://openaipublic.azureedge.net/clip/models/b8cca3fd41ae0c99ba7e8951adf17d267cdb84cd88be6f7c2e0eca1737a03836/ViT-L-14.pt)
- Flamingo9B:  https://huggingface.co/openflamingo/OpenFlamingo-9B/resolve/main/checkpoint.pt

However, after creating the model, when I load Flamingo weights, it given warning about missing keys. I can see all keys are related with `visual encoder` and `language encoder` as given here: (These are only start and end of visual and language encoder keys)

> _IncompatibleKeys(missing_keys=['vision_encoder.positional_embedding', 'vision_encoder.text_projection', 'vision_encoder.logit_scale', 'vision_encoder.visual.class_embedding', 'vision_encoder.visual.positional_embedding', 'vision_encoder.visual.proj',  **....,**   vision_encoder.token_embedding.weight', 'vision_encoder.ln_final.weight', 'vision_encoder.ln_final.bias', 'lang_encoder.model.layers.0.decoder_layer.self_attn.q_proj.weight', 'lang_encoder.model.layers.0.decoder_layer.self_attn.k_proj.weight', 'lang_encoder.model.layers.0.decoder_layer.self_attn.v_proj.weight',   **....,** 'lang_encoder.model.layers.31.decoder_layer.mlp.up_proj.weight', 'lang_encoder.model.layers.31.decoder_layer.input_layernorm.weight', 'lang_encoder.model.layers.31.decoder_layer.post_attention_layernorm.weight', 'lang_encoder.model.norm.weight', 'lang_encoder.lm_head.weight'], unexpected_keys=['vision_encoder.text_model.embeddings.position_ids', 'vision_encoder.vision_model.embeddings.position_ids'])

I hope Flamingo9B has partial weights (does not include vis/lang encoder weight. Please correct me if I am wrong. Thank you.

Q2: Is there any way to test the model on multiple GPUs?

**Comment by anas-awadalla** [comment]
1. This seems fine to me. The flamingo checkpoint doesn’t contain frozen weights which is what you are seeing here. If you test the model it should output something reasonable. 

2. Can you clarify what you mean by this? Do you want to shard the model across multiple gpus?

**Comment by mohbattharani** [comment]
1. Thank you. It can create some reasonable answers. 
2. Yes.

**Comment by anas-awadalla** [comment]
Ah ok unfortunately we don't support this right now. I think if you use [Otter's](https://github.com/Luodian/Otter/tree/main) wrapper on OpenFlamingo you can do this.
