### ISSUE TITLE
[FEATURE REQUEST] Support for OpenLLaMA

### ISSUE THREAD

**Issue by alfredplpl** [mlfoundations/open_flamingo#205]
**Is your feature request related to a problem? Please describe.**
Yes, the issue I'm experiencing is that your platform does not currently support integration with the OpenLLaMA large language model. As OpenLLaMA has gained considerable relevance in my line of work, its lack of compatibility disrupts the efficiency of my workflow.

https://huggingface.co/openlm-research/open_llama_7b

**Describe the workflow you want to enable.**
I'd like to be able to utilize OpenLLaMA's capabilities directly within your software, allowing for a more seamless exchange of information and processing of data.

**Describe your proposed solution.**
My proposal is to integrate support for the OpenLLaMA large language model within your software. This includes the ability to feed data to OpenLLaMA, receive and process outputs, and take full advantage of the features offered by OpenLLaMA within the environment of your software.

**Additional context**
OpenLLaMA is quickly becoming a vital tool in the realm of data science and AI, with its user base poised to increase in the future. By adding support for this model, your software could better cater to a broader user base, increasing its overall value and usability.

**Are you willing to help implement this feature?**
I am fully supportive of the implementation of this feature but regret to inform you that I lack the computational resources necessary to assist in its development. Nonetheless, I'm willing to contribute feedback and participate in user testing, as my expertise allows, once the feature is ready for trial.

**Comment by anas-awadalla** [comment]
Hello! Thank you for raising this issue. As the codebase already supports much better open LLMs we will not be adding openllama for now. Please let us know if you think we've missed something.
