### ISSUE TITLE
[FEATURE REQUEST] Timeline to release V2 weights

### ISSUE THREAD

**Issue by steve-marmalade** [mlfoundations/open_flamingo#208]
**Is your feature request related to a problem? Please describe.**
Hello, I noticed that the [README in the V2 branch](https://github.com/mlfoundations/open_flamingo/blob/attention_fix/README.md#initializing-an-openflamingo-model) contains several links to pretrained weights that are not available on huggingface yet. Is your plan to upload those when you merge that branch? I am wondering if I should wait for those to be released before testing out this model or if you expect it to be a little while.

Thanks for all of your effort!

**Comment by anas-awadalla** [comment]
Thank you for your interested! We are still working on this and yes we will share our new models when we merge that branch. In the meantime you can use our current checkpoint using the instructions on the main branch's README.
