### ISSUE TITLE
Feature Request: A function for video summary

### ISSUE THREAD

**Issue by javalisiddu** [mlfoundations/open_flamingo#211]
Hi, Is there a function to generate a summary for a given video sequence? If not, could you guide how to leverage this repository for video summarisation? 

Video Q&A is good but creating prompts to understand what’s happening in the video sequence is additional effort.

**Comment by i-gao** [comment]
Hi, apologies for the delay! OpenFlamingo currently only supports image inputs. We hope to train models that accept videos in the future!
