### ISSUE TITLE
Image-Sentence matching for MMC4 Dataset 

### ISSUE THREAD

**Issue by yassouali** [mlfoundations/open_flamingo#219]
Hello,

First, thanks for reproducing the Flamingo model.

I have a question regarding the preprocessing of a document from MMC4 (in [`preprocess_interleaved`](https://github.com/mlfoundations/open_flamingo/blob/63f85f4b3618a5f30ceb69e17a4adf70abd2ea1a/open_flamingo/train/data.py#L137)). For a given document with S sentences, and I images, each image is assigned to one of the sentences based on the CLIP image-text cosine similarities. While at first, I thought that this assignment was one-to-one (as mentioned in the [MMC4 Dataset](https://arxiv.org/pdf/2304.06939.pdf) paper), the function takes the argmax over all sentences for each image, and it is possible to assign many images to the same sentence. In this case, many `<|endofchunk|><image>` are appended next to each other, and if a sentence was assigned N images, the sentence tokens would only attend to the last one, and the first N-1 will not be attended to.

I was wondering if my understanding is correct and if this was indeed the desired behavior, and in this case, why not do a one-to-one assignment instead? 

Thank you

**Comment by i-gao** [comment]
Hi, apologies for the delay in responding! Thanks for bringing this to our attention -- this is a great point, and the current effect is not the desired behavior. 

For those training with MMC4 v1.1, it should suffice to use the `matched_text_index` field for each image instead of the argmax logic above. Would you be interested in submitting a PR to fix this quickly? Thanks!

**Comment by yassouali** [comment]
Hi, thanks for the answer.

For the PR, I certainly can. However, I did not quite understand the usage of `matched_text_index` you mentioned. But the implementation should be straightforward using scipy or scikit lean's linear assignment.

For example, here is a possible implementation of this:
```python
   # .....
   
    sim_matrix = info["similarity_matrix"]
    sentences = info["text_list"]
    
    # load images first to find which ones are valid
    valid_images, valid_image_indices = [], []
    for i, sample_image in enumerate(info["image_info"]):
        if "image_base64" not in sample_image:
            continue
        image_base64 = sample_image["image_base64"]
        rawbytes = base64.b64decode(image_base64)

        # filter to images >= 10KB
        if len(rawbytes) // 1000 <= MIN_KB:
            continue

        image = Image.open(io.BytesIO(rawbytes)).convert("RGB")
        valid_images.append(image)
        valid_image_indices.append(i)        

    sim_matrix = np.array(sim_matrix) # of shape images x sentences
    sim_matrix = sim_matrix[valid_image_indices]

    # negate the similarities to turn then into costs
    cost_matrix = - sim_matrix
    # find one to one assignements
    image_indices, sentence_indices = linear_sum_assignment(cost_matrix)

    images, sentence_ixs = [], []
    for i, sim_ix in zip(image_indices, sentence_indices):
        sim_score = sim_matrix[i][sim_ix]

        if sim_score < sim_threshold:
            continue

        images.append(valid_images[i])
        sentence_ixs.append(sim_ix)
        
    # .....
```

I can submit this as PR if this implementation is acceptable. Thanks.

**Comment by yassouali** [comment]
Hi, thanks for the answer.

For the PR, I certainly can. For the implementation, is it better to rerun the linear assignment during processing instead of using the precomputed ones in v1.1? This way, it will work with the different versions of the dataset and will also update the assignments in case some images are not valid after download.

For example, here is a possible implementation of this:
```python
from scipy.optimize import linear_sum_assignment

   # .....
   
    sim_matrix = info["similarity_matrix"]
    sentences = info["text_list"]
    
    # load images first to find which ones are valid
    valid_images, valid_image_indices = [], []
    for i, sample_image in enumerate(info["image_info"]):
        if "image_base64" not in sample_image:
            continue
        image_base64 = sample_image["image_base64"]
        rawbytes = base64.b64decode(image_base64)

        # filter to images >= 10KB
        if len(rawbytes) // 1000 <= MIN_KB:
            continue

        image = Image.open(io.BytesIO(rawbytes)).convert("RGB")
        valid_images.append(image)
        valid_image_indices.append(i)        

    sim_matrix = np.array(sim_matrix) # of shape images x sentences
    sim_matrix = sim_matrix[valid_image_indices]

    # negate the similarities to turn then into costs
    cost_matrix = - sim_matrix
    # find one to one assignements
    image_indices, sentence_indices = linear_sum_assignment(cost_matrix)

    images, sentence_ixs = [], []
    for i, sim_ix in zip(image_indices, sentence_indices):
        sim_score = sim_matrix[i][sim_ix]

        if sim_score < sim_threshold:
            continue

        images.append(valid_images[i])
        sentence_ixs.append(sim_ix)
        
    # .....
```

I can submit this as PR if this implementation is acceptable. Thanks.

**Comment by i-gao** [comment]
Thanks! Yes, this seems reasonable to me. :)

**Comment by yassouali** [comment]
See this pull request: https://github.com/mlfoundations/open_flamingo/pull/238
