### ISSUE TITLE
[BUG] Demo broken due to checksum error

### ISSUE THREAD

**Issue by innerop** [mlfoundations/open_flamingo#223]
Demo on HF is broken

RuntimeError: Model has been downloaded but the SHA256 checksum does not not match

## Expected Behavior

Should load normally

## Current Behavior

Produces error and doesn't load

## Steps to Reproduce

Try to relaunch the model on HF

```
from open_flamingo.src.flamingo import Flamingo
...
```

## Environment

HF

## Detailed Description

Tried to run the linked demo but it failed to launch

**Comment by anas-awadalla** [comment]
Thanks for pointing this out! I have reset it and it is working now. Let me know if you run into an issue.
