### ISSUE TITLE
The context_text of zero-shot and the performance of one-shot.

### ISSUE THREAD

**Issue by Holly-Max** [mlfoundations/open_flamingo#227]
Hello, recently I've been exploring the use of open_flaimngo to generate captions for MSCOCO. I've come across an interesting observation regarding its zero-shot and one-shot settings.

In the zero-shot case, the prompt includes two captions but without the image tags. This raises the question of why two captions are required in the generation process.

On the other hand, in the one-shot setting, I noticed a drop in performance of 5 scores compared to the zero-shot case. I'm curious to understand the reasons behind this decrease in performance when transitioning from zero-shot to one-shot.

I would greatly appreciate any insights or explanations regarding the necessity of providing two captions for the zero-shot case and the factors contributing to the decline in performance in the one-shot setting. Thank you.

**Comment by Holly-Max** [comment]
During the 1-shot testing process, I didn't encounter any apparent issues. However, when I used images that were quite similar as in-context examples, the output results almost always repeated the in-context label. Therefore, I believe your hypothesis is correct. The results of my 2-shot testing were three points higher than the 0-shot testing.

dDo you happen to know any methods that could potentially resolve this issue? Thanks!

**Comment by i-gao** [comment]
Okay! This is useful to know, thanks for looking into it!

You might consider an instruction-tuned version of OF, e.g. [Otter](https://github.com/Luodian/Otter).
