### ISSUE TITLE
[FEATURE REQUEST] Reduce pip dependencies to inference-time requirements.

### ISSUE THREAD

**Issue by DavidMChan** [mlfoundations/open_flamingo#230]
**Is your feature request related to a problem? Please describe.**
Currently, a number of the dependencies installed by default in the library are dependencies that are not required for inference in the model (such as wandb), which means that when users pip install the library, they get both the dependencies for inference, as well as the dependencies for training. This can cause issues for downstream libraries depending on this code for inference only, as they have to deal with dependency conflicts that aren't really conflicts, and increased installation size.

**Describe the workflow you want to enable.**
Alter the pip installation so that the only required dependencies are those necessary for inference.

**Describe your proposed solution.**
Move training/dev dependencies to their own optional requirements setup, i.e.
`pip install open-flamingo[training]`, `pip install open-flamingo[dev]`, `pip install open-flamingo[all]`
(or similar naming)

**Describe alternatives you've considered**
N/A - I don't know if there's any other way to do this. I suppose another way would be to tag an 'inference-only' release, or have a separate inference-only pip package, but that seems a bit excessive.

**Additional context**
This could be a breaking change in a lot of workflows, so there's a pretty wide number of things that need to be checked - this would be very helpful for usability though, and would reduce the need for library developers to maintain their own fork just for dependency resolution purposes.

**Are you willing to help implement this feature?**
Yes, however I'm not well versed in the code, so I don't know exactly what's required for inference. I ran into this issue with wandb (which for sure is not required for inference time), but there may be other dependencies that fall into the same category.

**Comment by anas-awadalla** [comment]
Hi David!

I totally agree with this. I think we can limit the pip package to inference requirements and move everything else to requirements-dev.txt. I will take this on.
