### ISSUE TITLE
labels in MMC4 FORWARD PASS

### ISSUE THREAD

**Issue by liyongqi67** [mlfoundations/open_flamingo#233]
I found the MMC4 FORWARD PASS will fail if the <image> is the first token of the input text.
In the train_one_epoch(), there is operation "labels[:, 0] = -100".
```
        labels = input_ids.clone()
        labels[labels == tokenizer.pad_token_id] = -100
        labels[:, 0] = -100  
        for i in range(labels.shape[0]):
            # remove loss for any token before the first <image> token
```
However, if the input text is ['<image>Two men, on smoking, talk outside a street-side restaurant.'], the labels will be:  
```
tensor([[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100]], device='cuda:1')
```
Because  "labels[:, 0] = -100" set the first <image> as -100, and "remove loss for any token before the first <image> token" will set all the tokens after the first <image> as -100.

**Comment by i-gao** [comment]
Hi, thanks for the catch! This line 
```
labels[:, 0] = -100  
```
should really be checking for the EOS token, which our tokenizer prepended by default when training. I'll revise the code to be
```
labels[labels == tokenizer.eos_token] = -100
```
Regarding your example, the input text needs to include an `<image>` token to have labels.

**Comment by liyongqi67** [comment]
Hi, I am sorry because I express the problem wrongly. 
I mean if the input text is ['\<image\>Two men, on smoking, talk outside a street-side restaurant.'], the labels will be:  
```
tensor([[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100]], device='cuda:1')
```
This is not what we expect, right?

**Comment by i-gao** [comment]
That's correct, the code on main has been updated to fix this.
