### ISSUE TITLE
How to set up multigpus?

### ISSUE THREAD

**Issue by Vaxxacavier** [mlfoundations/open_flamingo#234]
Hello,

I would like to run `mpt-7b` model using gpu. This model requires more than 16GB of VRAM, so I have to set up multigpus. I found out that there is a possibility to run this project using multigpus.
I can set up single gpu just by moving inputs to chosen gpu e.g. `.to('0')`. But how can I set up 2 or more gpus?

**Comment by anas-awadalla** [comment]
Hello! We don’t support running inference on multiple gpus. You may want to look at the [Otter repo](https://github.com/Luodian/Otter) supports multi gpu inference for OpenFlamingo.

**Comment by lziiid** [comment]
Hi, I would like to use mpt-7b too, but I encounter the problem `TypeError: forward() takes 2 positional arguments but 3 were given.`  Could you please provide me with your running environment (package versions) for me to debug? Thank you so much.

**Comment by anas-awadalla** [comment]
You can set up our exact environment using `conda env create -f environment.yml`. Also you should be using [this](https://huggingface.co/anas-awadalla/mpt-7b) version of mpt-7b.

**Comment by lziiid** [comment]
> You can set up our exact environment using `conda env create -f environment.yml`. Also you should be using [this](https://huggingface.co/anas-awadalla/mpt-7b) version of mpt-7b.

Thanks for your quick reply! My problem is solved. The reason is I use the [mosaicml/mpt-7b](https://huggingface.co/mosaicml/mpt-7b/discussions) in the readme file instead of [anas-awadalla-mpt-7b](https://huggingface.co/anas-awadalla/mpt-7b/tree/main).
