### ISSUE TITLE
dataset_flickr30k_coco_style.json

### ISSUE THREAD

**Issue by liyongqi67** [mlfoundations/open_flamingo#240]
Do you know if there is any script to obtain the dataset_flickr30k_coco_style.json file? I noticed that the dataset_flickr30k_coco_style.json is used for evaluation.

**Comment by anas-awadalla** [comment]
Sorry for the delay! I have uploaded all the annotation files [here](https://huggingface.co/datasets/openflamingo/eval_benchmark/tree/main) for easier access.
