### ISSUE TITLE
[BUG] You are using config.init_device='cpu', but you can also use config.init_device="meta" with Composer + FSDP for fast initialization.

### ISSUE THREAD

**Issue by DarkAlchy** [mlfoundations/open_flamingo#244]
Using your test script from the readme and the front page and I have never EVER had this happen before until I use yours.

![image](https://github.com/mlfoundations/open_flamingo/assets/10561690/8c6d266b-b11b-4768-a434-b5dcebb1abd7)
See those minimums?  Not sure how it is happening but something is messing around with my Ryzen stepping as everything else is fine on the CPU but I didn't even know it could go below 3.5ghz.

**Comment by DarkAlchy** [comment]
Figured out the cpu issue not how to get this to use the gpu.

**Comment by hhy150** [comment]
Hello, may I ask how this issue was resolved
