### ISSUE TITLE
Questions about compatibility between model version 1 and version 2

### ISSUE THREAD

**Issue by gray311** [mlfoundations/open_flamingo#246]
If I use LLAMA to initialize the Large Language Model (LLM) of OpenFlamingoV2 instead of MPT-7b, what impact would this have? It's like I only need to leverage the weights of the xttn layers and perceiver from OpenFlamingoV2. Would this result in a gap between different LLMs?

**Comment by gray311** [comment]
@anas-awadalla Thanks for your reply, that means if I want to use LLama-2 as openflamingo's LLM, I need to train perceiver modules and gated cross-attention layers from scratch, do I understand it correctly?

**Comment by anas-awadalla** [comment]
Yep

**Comment by gray311** [comment]
Thanks again for your reply!
