### ISSUE TITLE
Question around Generated Output

### ISSUE THREAD

**Issue by agneet42** [mlfoundations/open_flamingo#251]
Hi @anas-awadalla , thanks for the great work!
I am playing around with the model -- 

```
from open_flamingo import create_model_and_transforms
from PIL import Image
import requests
import torch


model, image_processor, tokenizer = create_model_and_transforms(
    clip_vision_encoder_path="ViT-L-14",
    clip_vision_encoder_pretrained="openai",
    lang_encoder_path="anas-awadalla/mpt-1b-redpajama-200b",
    tokenizer_path="anas-awadalla/mpt-1b-redpajama-200b",
    cross_attn_every_n_layers=1  # Defaults to ~/.cache
)
model = model.to('cuda')
demo_image_one = Image.open("NYU0001.jpg")

"""
Step 2: Preprocessing images

vision_x = [image_processor(demo_image_one).unsqueeze(0)]
vision_x = torch.cat(vision_x, dim=0)
vision_x = vision_x.unsqueeze(1).unsqueeze(0)


"""
Step 3: Preprocessing text
Details: In the text we expect an <image> special token to indicate where an image is.
 We also expect an <|endofchunk|> special token to indicate the end of the text 
 portion associated with an image.
"""
tokenizer.padding_side = "left" # For generation padding tokens should be on the left
lang_x = tokenizer(
    ["<image>Describe the Image"],
    return_tensors="pt",
)
print(vision_x.shape)
vision_x = vision_x.to('cuda')
lang_x = lang_x.to('cuda')
"""
Step 4: Generate text
"""
generated_text = model.generate(
    vision_x=vision_x,
    lang_x=lang_x["input_ids"],
    attention_mask=lang_x["attention_mask"],
    max_new_tokens=20
)

print("Generated text: ", tokenizer.decode(generated_text[0]))
```
The model generates the following answer - 

> Generated text:  <image>Describe the Image Image Image Image Image Image Image Image Image Image Image Image Image Image Image Image Image Image Image Image Image

Would you happen to know, why the model would generate such a weird output? I can also share the images if that would help. My input image is : 

![image](https://github.com/mlfoundations/open_flamingo/assets/22055826/96c03ef9-9440-4a2e-960e-acb8d139c106)

**Comment by anas-awadalla** [comment]
Hello! It doesn't look like you are loading the checkpoint weights into the model. Can you add [this](https://github.com/mlfoundations/open_flamingo#downloading-pretrained-weights) to your script.

**Comment by agneet42** [comment]
Thanks for the quick response! I added that. The outputs are somewhat better now. However, I notice, when I prompt the model for some questions, it answers by just appending the <|endofchunk|> token. Would you know the possible cause? 

`lang_x = tokenizer(
    ["<image>Are there equal number of apples and oranges in the image?"],
    return_tensors="pt",
)`

`Generated text:  <image>Are there equal number of apples and oranges in the image?<|endofchunk|>`

**Comment by agneet42** [comment]
I tried 1-shot, 3-shot and other prompts but the observation is about the same. Do you think I should try one of the larger models?

**Comment by anas-awadalla** [comment]
Yes, the 9B model is significantly better than the other ones. Can you try using more beams for the smaller model? Maybe you can also format the prompt as we do for other VQA tasks: "<image>Question:Are there equal number of A and B in the image? Answer:".

**Comment by agneet42** [comment]
Thanks @anas-awadalla , changing the # of beams and prompting in another way helped on the smaller model.
When, I try however on the 9B model, I get a `TypeError: forward() takes 2 positional arguments but 3 were given` error. I updated the encoders, the cross_attn_every_n_layers & the checkpoint_path. Would you happen to know the reason?

**Comment by agneet42** [comment]
No worries, it was an issue on my end. Thanks for the help!

**Comment by essamsleiman** [comment]
> Thanks @anas-awadalla , changing the # of beams and prompting in another way helped on the smaller model. When, I try however on the 9B model, I get a `TypeError: forward() takes 2 positional arguments but 3 were given` error. I updated the encoders, the cross_attn_every_n_layers & the checkpoint_path. Would you happen to know the reason?

Hey @agneet42 , I'm getting the same error. How did you fix it? Thanks!

**Comment by anas-awadalla** [comment]
I believe they weren't using the modified checkpoint https://huggingface.co/anas-awadalla/mpt-7b

**Comment by essamsleiman** [comment]
Thanks Anas!
