### ISSUE TITLE
Some questions about OpenFlamingo V1

### ISSUE THREAD

**Issue by SjokerLily** [mlfoundations/open_flamingo#252]
Hi @anas-awadalla , thanks for your great project!
 I am evaluating the VQAV2 task on OpenFlamingo V1 and V2. I have observed that OpenFlamingo V2 tends to exhibit lower performance as the number of in-context examples increases beyond 8 shots. In their paper, the authors speculate that this phenomenon may be attributed to the quality of pre-training data, which primarily comprises sequences with a small number of images (LAION-2B has a median of one image, while MMC4 has a median of two).
However, it seems that this phenomenon does not occur in OpenFlamingo V1, which performs better as the number of shots increases. Was OpenFlamingo V1 also pre-trained using sequences with few images? What are the median numbers of images and tokens per sequence in the pre-training data for OpenFlamingo V1?
Furthermore, apart from replacing the language model from LLaMA to MPT, have any other additional training methods been implemented in OpenFlamingo V2? As we can observe a significant improvement over V1, what specifically contributes to this enhanced performance?

**Comment by anas-awadalla** [comment]
Thanks for your interest @SjokerLily! 

First to clarify V2 models are trained on 12x more data than the V1 checkpoint and this is the main reason for the enhanced performance. I don't really have a good explanation for why V1  extrapolates better to more demonstrations. The data used to train both versions are the same. One reason could be different language model but I would need to run more experiments to verify this.

**Comment by SCZwangxiao** [comment]
> 12x more data

Thank you for the explanation! Could you explain more clearly what does `12x more data` means? By scaling larger datasets or iterating the original datasets 12x again?

**Comment by anas-awadalla** [comment]
We are using a larger dataset. We originally used only a fraction of multimodal c4 and Laion for v1.
