### ISSUE TITLE
How to finetune all paramaters, including vision_encoder and original decoder layers?

### ISSUE THREAD

**Issue by liyongqi67** [mlfoundations/open_flamingo#253]
I want to finetune all paramaters, and I set model.requires_grad_(True). However, I found the vision_encoder and original decoder layers cannot be trained.  The grad_requirs=True but the grad is None.
-->name: vision_encoder._fsdp_wrapped_module._fsdp_wrapped_module.ln_post.weight
-->para: -->name: vision_encoder._fsdp_wrapped_module._fsdp_wrapped_module.ln_post.weight
-->para: Parameter containing:
tensor([], device='cuda:1', requires_grad=True)
-->grad_requirs: True
-->grad_value: None

**Comment by anas-awadalla** [comment]
This is because of this [line](https://github.com/mlfoundations/open_flamingo/blob/a05dcba7c985ec22b55fb78fcef7bee62c78ef25/open_flamingo/src/flamingo.py#L194). If you remove that it should work fine.

**Comment by liyongqi67** [comment]
Many thanks!
