### ISSUE TITLE
Always reported OOM when train the model with LLama2

### ISSUE THREAD

**Issue by RyanYip-Kat** [mlfoundations/open_flamingo#259]
Here is the code I trained to use, setting the batch size always doesn't work.I used the single GPU A100,80G

torchrun --nnodes=1 --nproc_per_node=1 train.py \
  --lm_path ./llama-2-7b-chat-hf \
  --tokenizer_path ./llama-2-7b-chat-hf \
  --vision_encoder_path ViT-L-14 \
  --vision_encoder_pretrained openai \
  --cross_attn_every_n_layers 1 \
  --dataset_resampled \
  --learning_rate 1e-4 \
  --batch_size_mmc4 1 \
  --batch_size_laion 2 \
  --train_num_samples_mmc4 125000\
  --train_num_samples_laion 250000 \
  --loss_multiplier_laion 0.2 \
  --workers=4 \
  --run_name OpenFlamingo-9b-llama2 \
  --num_epochs 480 \
  --warmup_steps  1875 \
  --mmc4_textsim_threshold 0.24 \
  --laion_shards "PMCData_zipfiles/shardtar_files/shard-{0000..0001}.tar" \
  --mmc4_shards "ROCOData_zipfiles/shardtar_files/shard-{0000..0003}.tar" \
  --logging_steps 50

Could you tell how to solve this promble?Thanks!

**Comment by anas-awadalla** [comment]
You are setting cross attention every layer as done in `cross_attn_every_n_layers 1`. This will create a model way larger than 9B. If you change that to 4 it will have the correct number of parameters.

**Comment by RyanYip-Kat** [comment]
Ok，I had changed the cross_attn_every_n_layers=4,and it worked.Thanks~
