### ISSUE TITLE
[BUG] Train Utils Does Not Set `label=-100` for `eos_token_id`

### ISSUE THREAD

**Issue by loris2222** [mlfoundations/open_flamingo#269]
I think `train_utils.py` has a typo and labels for `eos_token`s are not correctly set to `-100`

## Expected Behavior
`eos_token` labels should be set to `-100`

## Current Behavior
`eos_token`s are not set to `-100` since matching is done with the string token and not the token id.

## Possible Implementation
Change `train_utils.py`: 
```
labels[labels == tokenizer.eos_token] = -100
```
To:
```
labels[labels == tokenizer.eos_token_id] = -100
```

**Comment by anas-awadalla** [comment]
Thanks for catching! I think we should be computing loss on eos tokens so this line can probably be removed.
