### ISSUE TITLE
Example for other pretrained language models

### ISSUE THREAD

**Issue by shomikj** [mlfoundations/open_flamingo#276]
Is there an example of how to initialize the OpenFlamingo model using other language models from the transformers package?

Specifically, how to call the create_model_and_transforms() function?

**Comment by anas-awadalla** [comment]
@shomikj Which model are you trying to use? It should just be the same as the example command [here](https://github.com/mlfoundations/open_flamingo#initializing-an-openflamingo-model) but replacing the lang_encoder_path and tokenizer_path with the model you want to use.
