### ISSUE TITLE
only call forwards -- blocking fsdp

### ISSUE THREAD

**Issue by mitchellnw** [mlfoundations/open_flamingo#91]
for all instances `x` of `nn.Module` we should only ever be `x(...)` for core loops like training

for instance this is not doing that
https://github.com/mlfoundations/open_flamingo/blob/try-c4/open_flamingo/src/flamingo_lm.py#L226-L228

i think it is possible to refactor to remove things like this

for instance pytorch even says not to call `x.forward(...)` because then the hooks are ignored, so really best to only do `x(...)`

**Comment by lorenmt** [comment]
Observed the exact same problem when I was developing Prismer.
Eventually came up with a solution to split the frozen and non-frozen modules by specifically adding a pre-defined condition:
https://github.com/NVlabs/prismer/blob/2fa4f8da37465eaf756d3bd4bc94dc44c15cc675/model/modules/roberta.py#L193-L198

**Comment by anas-awadalla** [comment]
Resolved in #202
